#pragma once
#include <memory>
#include <iostream>
#include "query_parser/AST.hpp"
class ExecutionEngine {
public:
    // This is the ONLY public function Rehan needs to call from main.cpp
    // It takes the clean AST generated by Arsalan's FrontendAPI.
    void execute(const std::unique_ptr<ASTNode>& ast);

private:
    // Rehan's internal routing functions. 
    // He will write the file handling and data logic inside these.
    
    // --- DDL ---
    void execute_create_table(const CreateTableStatement* stmt);

    // --- DML / DQL ---
    void execute_select(const SelectStatement* stmt);
    void execute_insert(const InsertStatement* stmt);
    void execute_update(const UpdateStatement* stmt);
    void execute_delete(const DeleteStatement* stmt);

    // --- TCL ---
    void execute_transaction(const TransactionStatement* stmt);
};
