# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/hasnat/Public/6th Semester/Advance DB/Project and Presentations/MyDB-Database-Engine"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/hasnat/Public/6th Semester/Advance DB/Project and Presentations/MyDB-Database-Engine"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/hasnat/Public/6th Semester/Advance DB/Project and Presentations/MyDB-Database-Engine/CMakeFiles" "/home/hasnat/Public/6th Semester/Advance DB/Project and Presentations/MyDB-Database-Engine//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/hasnat/Public/6th Semester/Advance DB/Project and Presentations/MyDB-Database-Engine/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named storage_engine

# Build rule for target.
storage_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 storage_engine
.PHONY : storage_engine

# fast build rule for target.
storage_engine/fast:
	$(MAKE) $(MAKESILENT) -f storage_engine/CMakeFiles/storage_engine.dir/build.make storage_engine/CMakeFiles/storage_engine.dir/build
.PHONY : storage_engine/fast

#=============================================================================
# Target rules for targets named system_schema

# Build rule for target.
system_schema: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 system_schema
.PHONY : system_schema

# fast build rule for target.
system_schema/fast:
	$(MAKE) $(MAKESILENT) -f system_schema/CMakeFiles/system_schema.dir/build.make system_schema/CMakeFiles/system_schema.dir/build
.PHONY : system_schema/fast

#=============================================================================
# Target rules for targets named query_parser

# Build rule for target.
query_parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 query_parser
.PHONY : query_parser

# fast build rule for target.
query_parser/fast:
	$(MAKE) $(MAKESILENT) -f query_parser/CMakeFiles/query_parser.dir/build.make query_parser/CMakeFiles/query_parser.dir/build
.PHONY : query_parser/fast

#=============================================================================
# Target rules for targets named planner

# Build rule for target.
planner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 planner
.PHONY : planner

# fast build rule for target.
planner/fast:
	$(MAKE) $(MAKESILENT) -f planner/CMakeFiles/planner.dir/build.make planner/CMakeFiles/planner.dir/build
.PHONY : planner/fast

#=============================================================================
# Target rules for targets named execution_engine

# Build rule for target.
execution_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 execution_engine
.PHONY : execution_engine

# fast build rule for target.
execution_engine/fast:
	$(MAKE) $(MAKESILENT) -f execution_engine/CMakeFiles/execution_engine.dir/build.make execution_engine/CMakeFiles/execution_engine.dir/build
.PHONY : execution_engine/fast

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/build
.PHONY : engine/fast

#=============================================================================
# Target rules for targets named mydb

# Build rule for target.
mydb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mydb
.PHONY : mydb

# fast build rule for target.
mydb/fast:
	$(MAKE) $(MAKESILENT) -f bin/CMakeFiles/mydb.dir/build.make bin/CMakeFiles/mydb.dir/build
.PHONY : mydb/fast

#=============================================================================
# Target rules for targets named test_disk_manager

# Build rule for target.
test_disk_manager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_disk_manager
.PHONY : test_disk_manager

# fast build rule for target.
test_disk_manager/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_disk_manager.dir/build.make tests/CMakeFiles/test_disk_manager.dir/build
.PHONY : test_disk_manager/fast

#=============================================================================
# Target rules for targets named test_page

# Build rule for target.
test_page: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_page
.PHONY : test_page

# fast build rule for target.
test_page/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_page.dir/build.make tests/CMakeFiles/test_page.dir/build
.PHONY : test_page/fast

#=============================================================================
# Target rules for targets named test_buffer_pool

# Build rule for target.
test_buffer_pool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_buffer_pool
.PHONY : test_buffer_pool

# fast build rule for target.
test_buffer_pool/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_buffer_pool.dir/build.make tests/CMakeFiles/test_buffer_pool.dir/build
.PHONY : test_buffer_pool/fast

#=============================================================================
# Target rules for targets named test_btree

# Build rule for target.
test_btree: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_btree
.PHONY : test_btree

# fast build rule for target.
test_btree/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_btree.dir/build.make tests/CMakeFiles/test_btree.dir/build
.PHONY : test_btree/fast

#=============================================================================
# Target rules for targets named test_transaction

# Build rule for target.
test_transaction: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_transaction
.PHONY : test_transaction

# fast build rule for target.
test_transaction/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_transaction.dir/build.make tests/CMakeFiles/test_transaction.dir/build
.PHONY : test_transaction/fast

#=============================================================================
# Target rules for targets named test_file_header

# Build rule for target.
test_file_header: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_file_header
.PHONY : test_file_header

# fast build rule for target.
test_file_header/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_file_header.dir/build.make tests/CMakeFiles/test_file_header.dir/build
.PHONY : test_file_header/fast

#=============================================================================
# Target rules for targets named test_partition

# Build rule for target.
test_partition: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_partition
.PHONY : test_partition

# fast build rule for target.
test_partition/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_partition.dir/build.make tests/CMakeFiles/test_partition.dir/build
.PHONY : test_partition/fast

#=============================================================================
# Target rules for targets named test_schema_file

# Build rule for target.
test_schema_file: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_schema_file
.PHONY : test_schema_file

# fast build rule for target.
test_schema_file/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_schema_file.dir/build.make tests/CMakeFiles/test_schema_file.dir/build
.PHONY : test_schema_file/fast

#=============================================================================
# Target rules for targets named test_relation_def

# Build rule for target.
test_relation_def: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_relation_def
.PHONY : test_relation_def

# fast build rule for target.
test_relation_def/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_relation_def.dir/build.make tests/CMakeFiles/test_relation_def.dir/build
.PHONY : test_relation_def/fast

#=============================================================================
# Target rules for targets named test_system_schema

# Build rule for target.
test_system_schema: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_system_schema
.PHONY : test_system_schema

# fast build rule for target.
test_system_schema/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_system_schema.dir/build.make tests/CMakeFiles/test_system_schema.dir/build
.PHONY : test_system_schema/fast

#=============================================================================
# Target rules for targets named test_database_file

# Build rule for target.
test_database_file: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_database_file
.PHONY : test_database_file

# fast build rule for target.
test_database_file/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_database_file.dir/build.make tests/CMakeFiles/test_database_file.dir/build
.PHONY : test_database_file/fast

#=============================================================================
# Target rules for targets named test_crypto

# Build rule for target.
test_crypto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_crypto
.PHONY : test_crypto

# fast build rule for target.
test_crypto/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_crypto.dir/build.make tests/CMakeFiles/test_crypto.dir/build
.PHONY : test_crypto/fast

#=============================================================================
# Target rules for targets named test_engine

# Build rule for target.
test_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_engine
.PHONY : test_engine

# fast build rule for target.
test_engine/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_engine.dir/build.make tests/CMakeFiles/test_engine.dir/build
.PHONY : test_engine/fast

#=============================================================================
# Target rules for targets named test_storage

# Build rule for target.
test_storage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_storage
.PHONY : test_storage

# fast build rule for target.
test_storage/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_storage.dir/build.make tests/CMakeFiles/test_storage.dir/build
.PHONY : test_storage/fast

#=============================================================================
# Target rules for targets named test_integration

# Build rule for target.
test_integration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_integration
.PHONY : test_integration

# fast build rule for target.
test_integration/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_integration.dir/build.make tests/CMakeFiles/test_integration.dir/build
.PHONY : test_integration/fast

#=============================================================================
# Target rules for targets named test_parser

# Build rule for target.
test_parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_parser
.PHONY : test_parser

# fast build rule for target.
test_parser/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_parser.dir/build.make tests/CMakeFiles/test_parser.dir/build
.PHONY : test_parser/fast

#=============================================================================
# Target rules for targets named test_exec_engine

# Build rule for target.
test_exec_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_exec_engine
.PHONY : test_exec_engine

# fast build rule for target.
test_exec_engine/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_exec_engine.dir/build.make tests/CMakeFiles/test_exec_engine.dir/build
.PHONY : test_exec_engine/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... engine"
	@echo "... execution_engine"
	@echo "... mydb"
	@echo "... planner"
	@echo "... query_parser"
	@echo "... storage_engine"
	@echo "... system_schema"
	@echo "... test_btree"
	@echo "... test_buffer_pool"
	@echo "... test_crypto"
	@echo "... test_database_file"
	@echo "... test_disk_manager"
	@echo "... test_engine"
	@echo "... test_exec_engine"
	@echo "... test_file_header"
	@echo "... test_integration"
	@echo "... test_page"
	@echo "... test_parser"
	@echo "... test_partition"
	@echo "... test_relation_def"
	@echo "... test_schema_file"
	@echo "... test_storage"
	@echo "... test_system_schema"
	@echo "... test_transaction"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

